hello-world

on:
  push:
    branches:
      - main

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: my first workflow  
      - uses: actions/checkout@v4
      - run: echo $"(cat hello_world.txt)"
    
